server:
  port: 8085

spring:
  application:
    name: battle-service
  rabbitmq:
    host: 82.97.244.140
    port: 5672
    username: gen_user
    password: UllXbQ168mlP4567UIGIUhiofd
    virtual-host: default_vhost
