server:
  port: 8085

spring:
  application:
    name: battle-service
  data:
    redis:
      database: 0
      host: 82.97.255.239
      port: 6379
      password: WXamUD1CUJnuBKLdjvf23
      timeout: 10000
      username: default

  rabbitmq:
    host: 82.97.244.140
    port: 5672
    username: gen_user
    password: UllXbQ168mlP4567UIGIUhiofd
    virtual-host: default_vhost
    listener:
      simple:
        concurrency: 10
        max-concurrency: 30
        retry:
          enabled: false
        prefetch: 1

