server:
  port: 8084

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://94.241.138.243:5432/default_db
    username: gen_user
    password: HWv6Yo4bIwI3FJjlk4357JHK
  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/db.changelog-master.xml
  jpa:
    showSql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
    database: postgresql
  application:
    name: statistic-service
    instance_id: ${random.uuid}
  rabbitmq:
    host: 82.97.244.140
    port: 5672
    username: gen_user
    password: UllXbQ168mlP4567UIGIUhiofd
    virtual-host: default_vhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  info:
    env:
      enabled: true
logging:
  file:
    name: "./logs/${spring.application.name}/${spring.application.instance_id}.log"