server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: resource
          uri: http://localhost:8081
          predicates:
            - Path=/middleware/**
          filters:
            - StripPrefix=1
            - TokenRelay=
            - AddUserHeaderFilter=
            - RemoveRequestHeader=cookie
            - RemoveRequestHeader=authorization

  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: 9d46780631ad4372b48ec4a44a56b75b
            client-secret: e56e640b3186472687f268d854c6fdd2
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: http://localhost:8080/login/oauth2/code/yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: login