server:
  port: 8081

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
  file:
    name: "./logs/${spring.application.name}/${spring.application.instance_id}.log"

spring:
  application:
    name: middleware-service
    instance_id: ${random.uuid}
  boot:
    admin:
      client:
        username: ${ADMIN_LOGIN}
        password: ${ADMIN_PASSWORD}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  info:
    env:
      enabled: true