server:
  port: 8081

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

spring:
  application:
    name: middleware-service