server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: ${CONFIG_GIT_URI}
          username: ${CONFIG_GIT_LOGIN}
          password: ${CONFIG_GIT_PASSWORD}
          default-label: main
          search-paths: "{application}"
  security:
      user:
        name: ${CONFIG_SECURITY_LOGIN}
        password: ${CONFIG_SECURITY_PASSWORD}