server:
  port: 8082

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://89.23.118.89:5432/default_db
    username: gen_user
    password: adZdfzCuo1xZdxhgf1674
  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/db.changelog-master.xml
  jpa:
    showSql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
    database: postgresql
