spring:
  application:
    name: crm-service
    instance_id: ${random.uuid}
  config:
    import: optional:configserver:http://app:a88ca849-dfcb-421d-b922-eb4a21dd9e96@localhost:8888
    cloud:
      config:
        fail-fast: true
