server:
  port: 8090

spring:
  application:
    name: battle-gateway-service
    instance_id: ${random.uuid}
  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: default_vhost
    listener:
      simple:
        concurrency: 30
        max-concurrency: 100
        retry:
          enabled: false
        prefetch: 1
  boot:
    admin:
      client:
        username: ${ADMIN_LOGIN}
        password: ${ADMIN_PASSWORD}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: ALWAYS