server:
  port: 8090

spring:
  application:
    name: battle-gateway-service
    instance_id: ${random.uuid}
  rabbitmq:
    host: 82.97.244.140
    port: 5672
    username: gen_user
    password: UllXbQ168mlP4567UIGIUhiofd
    virtual-host: default_vhost
    listener:
      simple:
        concurrency: 10
        max-concurrency: 30
        retry:
          enabled: false
        prefetch: 1
